//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIWorkout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        public int id { get; set; }
        public string day { get; set; }
        public string wotkout { get; set; }
        public string trainer { get; set; }
        public string image { get; set; }
    }
}
